---
# defaults file for deploy_nginx_lua
server_name: "{{ ansible_fqdn }}"

openresty_recommended_install: yes

# Packages installed for yum systems.
openresty_recommended_yum:
  - openresty-resty
  - openresty-opm
  - openresty-doc

# Protocol to be used for package download.
openresty_repo_protocol: https